### ISSUE TITLE
Error in "fpm run"

### ISSUE THREAD

**Issue by rajkumardongre** [interkosmos/fortran-xkcd#1]
Hi @interkosmos , I have followed all steps for installation as mentioned in the README.md file. Project is building correctly using `fpm build --profile=release`, but while running `fpm run` it's giving this error : 
 ```
rajkumar@DESKTOP-0VSJ5V8:~/opensource/gsoc/fortran-lang/fortran-xkcd$ fpm build --profile=release
Project is up to date
rajkumar@DESKTOP-0VSJ5V8:~/opensource/gsoc/fortran-lang/fortran-xkcd$ fpm run
Project is up to date
Contact Merge (2801)
Alt: I actually kind of feel like John and Surf King wouldn't like each other, which is a lot to unpack.

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7fb0e7343ad0 in ???
#1  0x7fb0e7342c35 in ???
#2  0x7fb0e704251f in ???
#3  0x7fb0e761d590 in ???
#4  0x7fb0e7981e6a in __xwin_MOD_xwin_destroy
        at ././src/xwin.f90:78
#5  0x7fb0e797ef55 in MAIN__
        at app/main.f90:54
#6  0x7fb0e797ef9c in main
        at app/main.f90:3
Segmentation fault (core dumped)
<ERROR> Execution for object " xkcd " returned exit code  139
<ERROR> *cmd_run*:stopping due to failed executions
STOP 139
```
I am running this WSL, I have also run [`fortran-xlib`](https://github.com/rajkumardongre/fortran-xlib) package examples, and they are working fine.

**Comment by interkosmos** [comment]
Thank you for reporting. Should be fixed with the last commit.
